### ISSUE TITLE
PDF Druck defekt mit aktueller Hibiscus Version?

### ISSUE THREAD

**Issue by karfau** [jverein/jverein#34]
Ich bekomme neuerdings die folgende Mitteilung wenn ich ein PDF erstellen will:

```
main loop crashed, retry
java.lang.NoSuchMethodError: com.itextpdf.text.pdf.PdfPTable.addCell(Lcom/itextpdf/text/pdf/PdfPCell;)V
	at de.jost_net.JVerein.io.Reporter.createHeader(Reporter.java:364)
	at de.jost_net.JVerein.io.Reporter.createHeader(Reporter.java:334)
	at de.jost_net.JVerein.gui.action.SpendenbescheinigungPrintAction.generiereSpendenbescheinigungStandardAb2014(SpendenbescheinigungPrintAction.java:948)
	at de.jost_net.JVerein.gui.action.SpendenbescheinigungPrintAction.handleAction(SpendenbescheinigungPrintAction.java:220)
	at de.jost_net.JVerein.gui.control.SpendenbescheinigungControl$4.handleAction(SpendenbescheinigungControl.java:527)
	at de.willuhn.jameica.gui.parts.Button$1$1.run(Button.java:174)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(Unknown Source)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:899)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Unknown Source)
	at org.eclipse.swt.widgets.Display.syncExec(Unknown Source)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:895)
	at de.willuhn.jameica.gui.parts.Button$1.widgetSelected(Button.java:168)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:916)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:327)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:75)
```
Das geschieht beim "drucken" von Spendenbescheinigung (Standard) oder Abrechnungslauflisten.
Damit geht ein großer Teil der Funktionalität des Programms gerade am Jahresanfang zu einem denkbar ungünstigen Zeitpunkt kaputt.

Die verwendeten Versionen:
JVerein: 2.8.17, Build 20180218 Build Nr. 520, DB-Version 417

Jamaica: 
Software-Version: 2.8.2
SWT-Version: 4629 / gtk
Java-Version: 1.8.0_212 / Linux amd64
Build: 450 [Datum 20180917]

HIbiscus: 
Software-Version: 2.8.8
HBCI4Java-Version: 3.0.22-SNAPSHOT
Datenbank-Version: 65
Build: 372 [Datum 20190103]

Mir drängt sich langsam der Eindruck auf, das diese Software nicht mehr mit aktuellen Jameica Versionen funktioniert und auch nicht mehr gewartet wird... weiß irgendjemand mehr dazu?

**Comment by karfau** [comment]
Ich konnte mein Problem "beheben" indem ich die Datei `itextpdf-5.3.3.jar` aus der Hibiscus Version 2.8.4 in das Installationsverzeichnis kopiert habe und die vorhandene `itextpdfß5.5.2.jar` in `itextpdfß5.5.2.jar.org` umbenannt habe.
Das ist ant[rlich nur eine temporäre Lösung, ddas nächste Update von Hibiscus wird das entweder rückgängig machen oder Probleme machen...

**Comment by NuvandaPV** [comment]
Selbes Problem hier. Ist eine Lösung in Aussicht?

**Comment by jverein** [comment]
Problem ist mit Version 2.8.18 beseitigt.
