### ISSUE TITLE
Unerwarteter Fehler in Buchführung > Buchungsklassen

### ISSUE THREAD

**Issue by Dathix** [jverein/jverein#55]
Stacktrace beim Öffnen der Buchungsklassen:

```
java.lang.NullPointerException
	at java.base/java.util.Calendar.setTime(Unknown Source)
	at de.jost_net.JVerein.gui.view.BuchungsklasseSaldoView.getYearBounds(BuchungsklasseSaldoView.java:86)
	at de.jost_net.JVerein.gui.view.BuchungsklasseSaldoView.bind(BuchungsklasseSaldoView.java:135)
	at de.willuhn.jameica.gui.GUI$5.run(GUI.java:711)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:908)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4905)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:904)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:594)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:529)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:566)
	at de.jost_net.JVerein.gui.action.BuchungsklasseSaldoAction.handleAction(BuchungsklasseSaldoAction.java:28)
	at de.willuhn.jameica.gui.Navigation.start(Navigation.java:371)
	at de.willuhn.jameica.gui.Navigation.access$500(Navigation.java:47)
	at de.willuhn.jameica.gui.Navigation$MyActionListener.handleEvent(Navigation.java:466)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3733)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:925)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:328)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:75)
```

**Comment by Ra-spi** [comment]
Habe die gleiche Fehlermeldung. Wann kann mit einer Lösung gerechnet werden?
*** Stacktrace ***

org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4621)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
	at org.eclipse.swt.widgets.Control.createHandle(Control.java:721)
	at org.eclipse.swt.widgets.Button.createHandle(Button.java:418)
	at org.eclipse.swt.widgets.Control.createWidget(Control.java:761)
	at org.eclipse.swt.widgets.Control.<init>(Control.java:115)
	at org.eclipse.swt.widgets.Button.<init>(Button.java:121)
	at de.willuhn.jameica.gui.style.StyleFactoryDefaultImpl.createButton(StyleFactoryDefaultImpl.java:33)
	at de.willuhn.jameica.gui.parts.Button.paint(Button.java:135)
	at de.willuhn.jameica.gui.parts.ButtonArea.paint(ButtonArea.java:51)
	at de.willuhn.jameica.gui.util.Container.addPart(Container.java:225)
	at de.jost_net.JVerein.gui.view.BuchungsklasseSaldoView.bind(BuchungsklasseSaldoView.java:145)
	at de.willuhn.jameica.gui.GUI$5.run(GUI.java:702)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:899)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4594)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:895)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:593)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:528)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:565)
	at de.jost_net.JVerein.gui.action.BuchungsklasseSaldoAction.handleAction(BuchungsklasseSaldoAction.java:28)
	at de.willuhn.jameica.gui.Navigation.start(Navigation.java:371)
	at de.willuhn.jameica.gui.Navigation.access$500(Navigation.java:47)
	at de.willuhn.jameica.gui.Navigation$MyActionListener.handleEvent(Navigation.java:466)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:916)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:327)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:75)

**Comment by Frankoli** [comment]
Der Fehler von @Ra-spi ist **nicht** der gleiche wie der ursprünglich eingetragene von @Dathix ! In diesem Issue geht es nur um die Nullpointer Exception. Bitte für den SWT Fehler einen neuen Issue eintragen, ansonsten geht der wahrscheinlich verloren.

**Comment by Ra-spi** [comment]
Neuen Issue erstellt:
[https://github.com/jverein/jverein/issues/66](url)
