### ISSUE TITLE
Fehlermeldung beim Erstellen von Buchführung --> Buchungsklassen

### ISSUE THREAD

**Issue by Ra-spi** [jverein/jverein#66]
Frankoli hat empfohlen den SWT Fehler neu einzutagen:
[https://github.com/jverein/jverein/issues/55](url)
Wann kann mit einer Lösung gerechnet werden?

*** Stacktrace ***

org.eclipse.swt.SWTError: No more handles
at org.eclipse.swt.SWT.error(SWT.java:4621)
at org.eclipse.swt.SWT.error(SWT.java:4510)
at org.eclipse.swt.SWT.error(SWT.java:4481)
at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
at org.eclipse.swt.widgets.Control.createHandle(Control.java:721)
at org.eclipse.swt.widgets.Button.createHandle(Button.java:418)
at org.eclipse.swt.widgets.Control.createWidget(Control.java:761)
at org.eclipse.swt.widgets.Control.(Control.java:115)
at org.eclipse.swt.widgets.Button.(Button.java:121)
at de.willuhn.jameica.gui.style.StyleFactoryDefaultImpl.createButton(StyleFactoryDefaultImpl.java:33)
at de.willuhn.jameica.gui.parts.Button.paint(Button.java:135)
at de.willuhn.jameica.gui.parts.ButtonArea.paint(ButtonArea.java:51)
at de.willuhn.jameica.gui.util.Container.addPart(Container.java:225)
at de.jost_net.JVerein.gui.view.BuchungsklasseSaldoView.bind(BuchungsklasseSaldoView.java:145)
at de.willuhn.jameica.gui.GUI$5.run(GUI.java:702)
at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
at de.willuhn.jameica.gui.GUI$6.run(GUI.java:899)
at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
at org.eclipse.swt.widgets.Display.syncExec(Display.java:4594)
at de.willuhn.jameica.gui.GUI.startSync(GUI.java:895)
at de.willuhn.jameica.gui.GUI.startView(GUI.java:593)
at de.willuhn.jameica.gui.GUI.startView(GUI.java:528)
at de.willuhn.jameica.gui.GUI.startView(GUI.java:565)
at de.jost_net.JVerein.gui.action.BuchungsklasseSaldoAction.handleAction(BuchungsklasseSaldoAction.java:28)
at de.willuhn.jameica.gui.Navigation.start(Navigation.java:371)
at de.willuhn.jameica.gui.Navigation.access$500(Navigation.java:47)
at de.willuhn.jameica.gui.Navigation$MyActionListener.handleEvent(Navigation.java:466)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
at de.willuhn.jameica.gui.GUI.loop(GUI.java:916)
at de.willuhn.jameica.gui.GUI.init(GUI.java:327)
at de.willuhn.jameica.system.Application.init(Application.java:145)
at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
at de.willuhn.jameica.Main.main(Main.java:75)
.
.
.
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4621)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
	at org.eclipse.swt.widgets.Control.createHandle(Control.java:721)
	at org.eclipse.swt.widgets.Button.createHandle(Button.java:418)
	at org.eclipse.swt.widgets.Control.createWidget(Control.java:761)
	at org.eclipse.swt.widgets.Control.<init>(Control.java:115)
	at org.eclipse.swt.widgets.Button.<init>(Button.java:121)
	at de.willuhn.jameica.gui.style.StyleFactoryDefaultImpl.createButton(StyleFactoryDefaultImpl.java:33)
	at de.willuhn.jameica.gui.parts.Button.paint(Button.java:135)
	at de.willuhn.jameica.gui.parts.ButtonArea.paint(ButtonArea.java:51)
	at de.willuhn.jameica.gui.util.Container.addPart(Container.java:225)
	at de.jost_net.JVerein.gui.view.BuchungsklasseSaldoView.bind(BuchungsklasseSaldoView.java:145)
	at de.willuhn.jameica.gui.GUI$5.run(GUI.java:702)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:899)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4594)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:895)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:593)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:528)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:565)
	at de.jost_net.JVerein.gui.action.BuchungsklasseSaldoAction.handleAction(BuchungsklasseSaldoAction.java:28)
	at de.willuhn.jameica.gui.Navigation.start(Navigation.java:371)
	at de.willuhn.jameica.gui.Navigation.access$500(Navigation.java:47)
	at de.willuhn.jameica.gui.Navigation$MyActionListener.handleEvent(Navigation.java:466)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:916)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:327)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:75)

**Comment by Frankoli** [comment]
Gibt wohl mehrere Threads zu diesem Fehler, hier kurz aufgelistet:

- [Fehler beim Öffnen der Buchungsklassen (10.4.2020)](https://jverein-forum.de/viewtopic.php?f=5&t=7054)
- [Fehlermeldung beim Erstellen des Buchungsklassen Saldo (17.1.2020)](https://jverein-forum.de/viewtopic.php?f=5&t=7007)
- [Unerwarteter Fehler beim Aufruf Buchführung -> Buchungsklassen (12.7.2019)](https://jverein-forum.de/viewtopic.php?f=5&t=6738)

Bisheriger Kenntnisstand:
- Die Fehlermeldung deutet darauf hin, dass zu viele SWT Handles (also mehr oder weniger GUI-Elemente) vom Programm erstellt werden. Das Limit liegt wohl bei Nutzerprogrammen bei etwa 10.000 Handles, die jverein im Normalbetrieb bei weitem unterschreitet. 
- In einem [Forumsbeitrag](https://jverein-forum.de/viewtopic.php?p=18092#p18092) wurde zudem erwähnt, dass der Fehler bei Verwendung der Version 2.8.18 auftritt, aber in 2.8.17 nicht. Entsprechende Codeänderungen für die Seite "Buchungsklassen" wurden im Pull-Request #38 angezogen. 
- Die Codeänderung beinhaltet eine Schleife, die entsprechende SWT Handles erstellt. Durch Experimentieren bekam ich nach etwa 9000 Loops die gleiche Fehlermeldung, die so häufig gepostet wurde.
- Die Anzahl an Schleifendurchläufen ist abhängig vom ersten und letzten Jahr der in der Datenbank gespeicherten Buchungen. Z.B.: Früheste Buchung in 2005, späteste Buchung in 2020 ergibt 16 Durchgänge.  

**Vermutung:
Die Rückgabewerte der Datenbank sind fehlerhaft, wodurch massiv zu viele Schleifendurchgänge generiert werden.** 

Wurde im Zuge des Versionsupdates von jverein möglicherweise auch die Datenbankstruktur angepasst? Das Problem taucht bei der Erstinstallation von jverein Version 2.8.18 jedenfalls nicht auf. Oder haben die betroffenen Benutzer womöglich eine deutlich ältere Datenbank, die mit der gemachten Änderung nicht mehr kompatibel ist? Ist da jemand mehr im Thema Datenbanken drin? Bin hier noch neu...

**Comment by Frankoli** [comment]
Ok, also ich kann mir nicht vorstellen, dass sich die Tabellenstruktur für Buchungen in der Datenbank so verändert hat, dass das Datum der Buchung irgendwann mal nicht abgespeichert wurde. Wäre zumindest recht unlogisch, da es sich um ein offensichtlich essentielles Feld handelt.

Daher 2 mögliche Erklärungen (basierend auf meiner letzten Vermutung):
1. Das Datum mindestens einer Buchung wurde irgendwann einmal (möglicherweise technisch bedingt) falsch in der Datenbank abgespeichert. Heißt z.B., die Jahreszahl des Datums ist komplett utopisch. 
2. Der Benutzer hat mindestens eine Buchung durchgeführt, die vielleicht als Test genutzt wurde, mit einem absichtlich falschen Datum. Wie z.B. 01.01.9999. Wenn solche Mondwerte noch irgendwo in der Datenbank existieren, dann könnten die zu dem angesprochenen Fehler führen.

Am einfachsten ließe sich das klären, wenn jemand mit dem genannten Fehler seine Datenbank auf diesen Verdacht hin untersucht. Das würde ich auch übernehmen, allerdings bezweifle ich, dass mir jemand seine private Datenbank zur Verfügung stellt. Zumindest würde ich gerne meinen Verdacht soweit zunächst verifizieren lassen, ein Lösungsansatz ist dann recht schnell aus der Tasche gezaubert.

**Comment by Ra-spi** [comment]
Hallo Frankoli, danke für Deine Infos. Ich versuche einmal die DB nach dem Mondwert zu durchsuchen.
Ob es mir gelingt weis ich nicht da das Geschäftsjahr 2019 schon abgeschlossen ist.

**Comment by Frankoli** [comment]
Die entsprechende SQL-Abfrage, die du testen kannst und auch im Programm genutzt wird ist folgende:
**"select min(datum) as val from buchung"** und
**"select max(datum) as val from buchung"**

Ob das Geschäftsjahr abgeschlossen ist oder nicht, dürfte aber irrelevant sein. Wenn ich das richtig überblicke, dann beinhaltet die Tabelle "Buchung" nämlich alle jemals durchgeführten Buchungen.

**Comment by Ra-spi** [comment]
SQL-Abfrage in welcher Datenbank?
ich habe einen csv Export gestartet und dort standen keine falschen Datumsdaten drin.

**Comment by Frankoli** [comment]
Benutzt du für jverein die normale H2 Datenbank oder hast du eine eigene mit MySQL erzeugt? Vielleicht kann Sqliteman nicht mit der H2 Datenbank umgehen, weil die entsprechenden Treiber fehlen. Hab mir kurz mal RazorSQL geladen, damit kann ich die H2 Datenbank (jverein.mv.db) problemlos öffnen und SQL-Abfragen (die oben geposteten) absenden. Aber bloß daran denken jverein zu schließen, bevor du eine Verbindung mit einem externen Programm aufbaust!

Der CSV Export wird ja nur die im Programm vorgefilterten Daten exportieren, das hilft leider nicht.

**Comment by Ra-spi** [comment]
Ich nutze die normale H2 Datenbank.
Ich habe die Trialversion von RazorSQL installiert.
Die H2 Datenbank (jverein.mv.db) läst sich leider nicht mit meinem Nutzername und Passwort nicht öffnen.

**Comment by Ra-spi** [comment]
Passwort im Jverein-Forum gefunden

**Comment by Frankoli** [comment]
Ok, damit ist die gute Nachricht, dass meine Vermutung richtig war. Heißt, ich kann da eine Überprüfung mit einbauen, um dieses Problem zu vermeiden. Oder der ursprüngliche Autor der Codeänderung macht das, mir egal. Danke für deine Mithilfe!

Login und Passwort für die Datenbank stehen auch in der Doku von jverein. Jetzt verstehst du, warum ich meinen letzten Beitrag nochmal schnell editiert habe mit dem Zusatz, die Verbindung zur Datenbank nur **lesend** aufzubauen. Es ging mir nur darum, meine Vermutung der Problemursache zu verifizieren. Händische Änderungen in der Datenbank sollten immer nur durchgeführt werden, wenn man vorher eine Sicherheitskopie angelegt hat und weiß was man tut. 

Bitte sag mir, dass du jverein soweit ganz normal weiter verwenden kannst, mit deinen ganzen Daten. Der eine falsche Eintrag ist nicht so wild, besser als eine komplett korrumpierte DB.

**Comment by Ra-spi** [comment]
Ich habe mit einer Kopie gearbeitet. Beim Speichern mit RazorSQL wurde nur eine .sql erzeugt die ichleider in jverein nicht nutzen kann. Ich hatte jetzt H2 Database Engine versucht die jverein.mv.db zu bearbeiten.
-- | --

**Comment by Frankoli** [comment]
Puh, da fällt mir ein Stein vom Herzen :)
Die .sql wird nur deine Query enthalten, oder? Grob müsste es so laufen, dass du per SQL-Query den von dir gefundenen Eintrag anziehst und das Datum per `update` bearbeitest. Eigentlich sollte egal sein, mit welchem Tool du die Query an die DB stellst, hauptsache du bist damit verbunden.

Ich probier mal mein Glück (bitte nur an der Kopie ausprobieren):
```
UPDATE buchung
SET datum = '2018-02-26'
WHERE datum = '20018-02-26';
```

**Comment by Ra-spi** [comment]
Hallo Frankoli,
ich habe heute mit der RazorSQL-Trialversion in der Kopie der Wirkversion von jverein.mv.db die überzählige "0" nach Deiner Anweisung gelöscht. Nach dem Neustart der Vereinsverwaltung konnte ich nun endlich das Buchungsklassen-Salto fehlerfrei ansehen und ausdrucken.
Noch einmal vielen Dank für Deine SQL-Tipps, ohne die hätte ich dises falsche Null nie gefunden.

Danke ! Danke! Danke!
