### ISSUE TITLE
NullPointerException when assigning a transaction without purpose field to a member account

### ISSUE THREAD

**Issue by INuvanda** [jverein/jverein#70]
# Steps to reproduce

1. Select a transaction that has an empty field for the transaction purpose (dt. “Verwendungszweck”)
2. Assign that transaction to a member account
3. Observe failure

# Expected behavior

The transaction is assigned to the member account.

# Observed behavior

Assigning fails with a NullPointerException

# Log

```
java.lang.NullPointerException
	at de.jost_net.JVerein.server.MitgliedskontoImpl.insertCheck(MitgliedskontoImpl.java:75)
	at de.willuhn.datasource.db.AbstractDBObject.insert(AbstractDBObject.java:649)
	at de.willuhn.datasource.db.AbstractDBObject.store(AbstractDBObject.java:314)
	at de.jost_net.JVerein.gui.action.BuchungMitgliedskontoZuordnungAction.handleAction(BuchungMitgliedskontoZuordnungAction.java:105)
	at de.willuhn.jameica.gui.parts.ContextMenu$1.handleEvent(ContextMenu.java:183)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4385)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3789)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:928)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:331)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:75)
```

# Additional observations

I think the problem could be worked around by changing this line as follows:

https://github.com/jverein/jverein/blob/6212a59b4f995383e6594c4bafa1289547681ef7/src/de/jost_net/JVerein/server/MitgliedskontoImpl.java#L171

```
Object result = getAttribute("Zweck1");
if (result instanceof String) {
    return (String) result;
} else {
    return '';
}
```

I don't currently have the means to test this though.

**Comment by NuvandaPV** [comment]
Oh, I forgot:

I am running JVerein 2.8.18 on Jameica 2.10.0 with Hibiscus 2.10.0.

**Comment by kpatzwald** [comment]
Hi,

what kind of transaction do you mean? I tried it with "Buchungen". I created a new Buchung without purpose ("Vewendungszweck"). When I try to assign it to a member I get an error message in the app "Verwendungszweck fehlt".

![Bildschirmfoto 2022-11-10 um 08 44 07](https://user-images.githubusercontent.com/73938015/201029900-c50f69b0-8024-43d3-bfc0-6805cf223561.png)

Maybe already fixed?

Best regards
Kay
