### ISSUE TITLE
NullPointerException bei Sollbuchung

### ISSUE THREAD

**Issue by Turakar** [jverein/jverein#74]
# Fehlerbeschreibung
Beim Erstellen einer neuen Sollbuchung entsteht folgender Fehler. Können Sie bei der Behebung des Fehlers helfen? Der Fehler wurde auch im [Forum](https://www.jverein-forum.de/viewtopic.php?t=6977) berichtet.

# Stacktrace
```
java.lang.NullPointerException
 at de.jost_net.JVerein.gui.control.MitgliedskontoControl.getBuchungsart(MitgliedskontoControl.java:294)
 at de.jost_net.JVerein.gui.view.MitgliedskontoDetailView.bind(MitgliedskontoDetailView.java:51)
 at de.willuhn.jameica.gui.GUI$5.run(GUI.java:714)
 at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
 at de.willuhn.jameica.gui.GUI$6.run(GUI.java:911)
 at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
 at org.eclipse.swt.widgets.Display.syncExec(Display.java:5048)
 at de.willuhn.jameica.gui.GUI.startSync(GUI.java:907)
 at de.willuhn.jameica.gui.GUI.startView(GUI.java:597)
 at de.jost_net.JVerein.gui.action.MitgliedskontoDetailSollNeuAction.handleAction(MitgliedskontoDetailSollNeuAction.java:57)
 at de.willuhn.jameica.gui.parts.ContextMenu$1.handleEvent(ContextMenu.java:183)
 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4441)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
 at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4227)
 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3837)
 at de.willuhn.jameica.gui.GUI.loop(GUI.java:928)
 at de.willuhn.jameica.gui.GUI.init(GUI.java:331)
 at de.willuhn.jameica.system.Application.init(Application.java:145)
 at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
 at de.willuhn.jameica.Main.main(Main.java:78)
 ```

# Versionen
JVerein: 2.8.18
Jameica: 2.10.2
Hibiscus: 2.10.5
OS: MacOS 10.15.7

**Comment by kpatzwald** [comment]
Problem ist in https://github.com/openjverein/jverein/pull/21 behoben.
