### ISSUE TITLE
v2.8.20 Mail defekt

### ISSUE THREAD

**Issue by dieseyer** [jverein/jverein#86]
Hallo zusammen,

aktuell benutze ich v2.8.18 von    jverein.de/updates/

In meiner Testumgebung habe ich ein Update auf v2.8.19 von   https://openjverein.github.io/jameica-repository/ 
durchgeführt. Mail i.O.
Anschließend habe ich ein Update auf v2.8.20 von   https://openjverein.github.io/jameica-repository/ 
durchgeführt; Fehler in   JVerein - Administratation - Einstellungen - Mail 

<code>
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.<init>(Integer.java:1105)
	at de.jost_net.JVerein.gui.control.EinstellungControl.getImapPort(EinstellungControl.java:1103)
	at de.jost_net.JVerein.gui.view.EinstellungenMailView.bind(EinstellungenMailView.java:57)
	at de.willuhn.jameica.gui.GUI$5.run(GUI.java:711)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:908)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5941)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:904)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:594)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:529)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:566)
	at de.jost_net.JVerein.gui.action.AdministrationEinstellungenMailAction.handleAction(AdministrationEinstellungenMailAction.java:28)
	at de.willuhn.jameica.gui.Navigation.start(Navigation.java:371)
	at de.willuhn.jameica.gui.Navigation.access$500(Navigation.java:47)
	at de.willuhn.jameica.gui.Navigation$MyActionListener.handleEvent(Navigation.java:466)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:925)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:328)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:75)
</code>

**Comment by EisW** [comment]
Ich kann den Fehler bestätigen.

Was passiert: Das Feld Einstellungen.ImapPort (der von JVerein nicht benötigt wird, da keine eingehenden Mails betrachtet werden) darf nicht leer sein, ist es aber auch bei mir.

Workaround: habe die Datenbank mit Openoffice geöffnet und dort 993 eingetragen, dann ist der eMail-Duialog wieder zu sehen. 

Lösung: Erfordenriss für Posteingang sollte entschärft werden...

**Comment by dieseyer** [comment]
Guter Hinweis. 

Für einen Test habe ich vor dem Update auf v2.8.20 den IMAP Port 993 eingetragen.

( _Datenbank mit Openoffice öffnen_  Habe ich mit LibreOffice bisher nicht hinbekommen. Ich nehme phpMyAdmin.)
